const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('claudeAPI', {
  getPathForFile: (file) => webUtils.getPathForFile(file),
  runClaude: (prompt, continueConversation) => ipcRenderer.invoke('run-claude', prompt, continueConversation),
  stopClaude: () => ipcRenderer.invoke('stop-claude'),
  onStream: (callback) => ipcRenderer.on('claude-stream', (event, data) => callback(data)),
  onStreamError: (callback) => ipcRenderer.on('claude-stream-error', (event, data) => callback(data)),
  onAutoSyncStart: (callback) => ipcRenderer.on('auto-sync-start', () => callback()),
  onAutoSyncEnd: (callback) => ipcRenderer.on('auto-sync-end', () => callback()),
  saveHistory: (messages) => ipcRenderer.invoke('save-history', messages),
  loadHistory: () => ipcRenderer.invoke('load-history'),
  getUsage: () => ipcRenderer.invoke('get-usage'),
  getPromptStats: () => ipcRenderer.invoke('get-prompt-stats'),
  getGitStats: () => ipcRenderer.invoke('get-git-stats'),
  getGitLog: () => ipcRenderer.invoke('get-git-log'),
  getGitDiff: (hash) => ipcRenderer.invoke('get-git-diff', hash),
  getVault: () => ipcRenderer.invoke('get-vault'),
  getVaultFile: (type, name) => ipcRenderer.invoke('get-vault-file', { type, name }),
  renameVaultFile: (type, oldName, newName) => ipcRenderer.invoke('rename-vault-file', { type, oldName, newName }),
  deleteVaultFile: (type, name) => ipcRenderer.invoke('delete-vault-file', { type, name }),
  importFile: (sourcePath) => ipcRenderer.invoke('import-file', sourcePath),
  exportChat: (content) => ipcRenderer.invoke('export-chat', content),
  listSessions: () => ipcRenderer.invoke('list-sessions'),
  getSession: (id) => ipcRenderer.invoke('get-session', id),
  getConfig: () => ipcRenderer.invoke('get-config'),
  addVault: (name, path) => ipcRenderer.invoke('add-vault', { name, path }),
  updateVault: (originalName, name, path) => ipcRenderer.invoke('update-vault', { originalName, name, path }),
  removeVault: (name) => ipcRenderer.invoke('remove-vault', name),
  setActiveVault: (name) => ipcRenderer.invoke('set-active-vault', name),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  updateAutoSync: (autoSync) => ipcRenderer.invoke('update-auto-sync', autoSync),
  setTheme: (theme) => ipcRenderer.invoke('set-theme', theme),
  setModel: (model) => ipcRenderer.invoke('set-model', model),
  addAction: (label, prompt) => ipcRenderer.invoke('add-action', { label, prompt }),
  updateAction: (id, label, prompt) => ipcRenderer.invoke('update-action', { id, label, prompt }),
  removeAction: (id) => ipcRenderer.invoke('remove-action', id),
  addPreset: (label, systemPrompt) => ipcRenderer.invoke('add-preset', { label, systemPrompt }),
  updatePreset: (id, label, systemPrompt) => ipcRenderer.invoke('update-preset', { id, label, systemPrompt }),
  removePreset: (id) => ipcRenderer.invoke('remove-preset', id),
  searchVault: (query) => ipcRenderer.invoke('search-vault', query),
  searchSessions: (query) => ipcRenderer.invoke('search-sessions', query),
  getWikiGraph: () => ipcRenderer.invoke('get-wiki-graph'),
  getWorkingDiff: () => ipcRenderer.invoke('get-working-diff'),
  listTrash: () => ipcRenderer.invoke('list-trash'),
  restoreVaultFile: (type, name) => ipcRenderer.invoke('restore-vault-file', { type, name }),
  emptyTrash: () => ipcRenderer.invoke('empty-trash'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  checkForAppUpdates: () => ipcRenderer.invoke('check-for-app-updates'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (event, data) => callback(data)),
  getAutoLaunch: () => ipcRenderer.invoke('get-auto-launch'),
  setAutoLaunch: (enabled) => ipcRenderer.invoke('set-auto-launch', enabled),
  exportConfig: () => ipcRenderer.invoke('export-config'),
  importConfig: () => ipcRenderer.invoke('import-config'),
  setLanguage: (language) => ipcRenderer.invoke('set-language', language),
  setUserName: (userName) => ipcRenderer.invoke('set-user-name', userName),
  togglePin: (category, id) => ipcRenderer.invoke('toggle-pin', { category, id }),
  pickImage: () => ipcRenderer.invoke('pick-image'),
});
